#Server Port Configuration
server:
  port: 8081

#Spring Database Postgres Sql Configuration
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

  config:
    import: optional:configserver:http://localhost:8085

# It includes the application name but above one will only import the config no name.
#  config:
#    import:
#      optional:
#        configServer:http://localhost:8085


#Server Configuration
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8888/eureka
#   profile:
#     active: dev
