#Server Port
server:
  port: 8085



#Server config from Git Repository
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Dragonoid9/microservice-config.git
          clone-on-start: true
